// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SistemaDeConsultasMedicas.Models;

public partial class Consultories_System_Context : DbContext
{
    public Consultories_System_Context()
    {
    }

    public Consultories_System_Context(DbContextOptions<Consultories_System_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<APIs> APIs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=192.168.193.35,1433;Initial Catalog=Consultories_System_Dev;Persist Security Info=True;TrustServerCertificate=True;Encrypt=True;MultipleActiveResultSets=true;User ID=UTSC_USER;Password=S1stem@5.UTSC2025");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("db_datareader");

        modelBuilder.Entity<APIs>(entity =>
        {
            entity.HasKey(e => e.Id_API);

            entity.ToTable("APIs", "dbo");

            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.URL)
                .IsRequired()
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}