// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDeConsultasMedicas.Models;

public partial class Medical_Appointments
{
    public int Id_Appointment { get; set; }

    public int fk_Doctor { get; set; }

    public int fk_Patient { get; set; }

    public int fk_Schedule { get; set; }

    public DateOnly Date { get; set; }

    public string Notes { get; set; }

    public virtual Users fk_DoctorNavigation { get; set; }

    public virtual Users fk_PatientNavigation { get; set; }

    public virtual Schedules fk_ScheduleNavigation { get; set; }
}