// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSM_BlazorHybridApp.Models;

public partial class APIs
{
    public int Id_API { get; set; }

    public string Name { get; set; }

    public string URL { get; set; }

    public bool IsGet { get; set; }

    public bool IsPost { get; set; }
}