// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Services.Data;

public partial class Status
{
    public int Id_Status { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Medical_Appointments> Medical_Appointments { get; set; } = new List<Medical_Appointments>();
}