// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebServices.Data;

public partial class Consultories_System_DevContext : DbContext
{
    public Consultories_System_DevContext()
    {
    }

    public Consultories_System_DevContext(DbContextOptions<Consultories_System_DevContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Consultories> Consultories { get; set; }

    public virtual DbSet<Medical_Appointments> Medical_Appointments { get; set; }

    public virtual DbSet<Municipalities> Municipalities { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Sexes> Sexes { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<Types> Types { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WIN-BNES3C0B631;Initial Catalog=Consultories_System_Dev;Persist Security Info=True;TrustServerCertificate=True;Encrypt=True;MultipleActiveResultSets=true;User ID=UTSC_USER;Password=S1stem@5.UTSC2025");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Consultories>(entity =>
        {
            entity.HasKey(e => e.Id_Consultory).HasName("PK__Consulto__F3FE3AA1F06DB25E");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Email)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Latitude)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Length)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);

            entity.HasOne(d => d.fk_MunicipalityNavigation).WithMany(p => p.Consultories)
                .HasForeignKey(d => d.fk_Municipality)
                .HasConstraintName("FK_Consultories_Municipalities");
        });

        modelBuilder.Entity<Medical_Appointments>(entity =>
        {
            entity.HasKey(e => e.Id_Appointment).HasName("PK__Medical___6ECCF90272C33560");

            entity.Property(e => e.Appointment_Date).HasColumnType("date");
            entity.Property(e => e.Created_Date).HasColumnType("date");

            entity.HasOne(d => d.fk_DoctorNavigation).WithMany(p => p.Medical_Appointmentsfk_DoctorNavigation)
                .HasForeignKey(d => d.fk_Doctor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MEDICAL_APPOINTMENTS_DOCTOR_USERS");

            entity.HasOne(d => d.fk_PatientNavigation).WithMany(p => p.Medical_Appointmentsfk_PatientNavigation)
                .HasForeignKey(d => d.fk_Patient)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MEDICAL_APPOINTMENTS_PATIENT_USERS");

            entity.HasOne(d => d.fk_StatusNavigation).WithMany(p => p.Medical_Appointments)
                .HasForeignKey(d => d.fk_Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Medical_Appointments_Status");
        });

        modelBuilder.Entity<Municipalities>(entity =>
        {
            entity.HasKey(e => e.Id_Municipality);

            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.Id_Role).HasName("PK__Roles__34ADFA60F6D42105");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Sexes>(entity =>
        {
            entity.HasKey(e => e.Id_Sex).HasName("PK__Sexes__552797C2CF2CBD0C");

            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id_Status).HasName("PK_STATUS");

            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Types>(entity =>
        {
            entity.HasKey(e => e.Id_Type).HasName("PK__Types__1A20A3D52B0AE14A");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id_User).HasName("PK__Users__D03DEDCB49E61E8F");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Email)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Phone).IsUnicode(false);

            entity.HasOne(d => d.fk_ConsultoryNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fk_Consultory)
                .HasConstraintName("FK_USERS_CONSULTORIES");

            entity.HasOne(d => d.fk_RoleNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fk_Role)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_USERS_ROLES");

            entity.HasOne(d => d.fk_SexNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fk_Sex)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_USERS_SEXES");

            entity.HasOne(d => d.fk_TypeNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fk_Type)
                .HasConstraintName("FK_USERS_TYPES");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}