// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServices.Data;

public partial class Medical_Appointments
{
    public int Id_Appointment { get; set; }

    public int fk_Doctor { get; set; }

    public int fk_Patient { get; set; }

    public int fk_Status { get; set; }

    public DateTime Created_Date { get; set; }

    public DateTime Appointment_Date { get; set; }

    public string Notes { get; set; }

    public virtual Users fk_DoctorNavigation { get; set; }

    public virtual Users fk_PatientNavigation { get; set; }

    public virtual Status fk_StatusNavigation { get; set; }
}