// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServices.Data;

public partial class Municipalities
{
    public int Id_Municipality { get; set; }

    public string Name { get; set; }

    public int Zip_Code { get; set; }

    public virtual ICollection<Consultories> Consultories { get; set; } = new List<Consultories>();
}