// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServices.Data;

public partial class Users
{
    public int Id_User { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public int fk_Sex { get; set; }

    public int fk_Role { get; set; }

    public int? fk_Consultory { get; set; }

    public int? fk_Type { get; set; }

    public bool Active { get; set; }

    public bool Login { get; set; }

    public virtual ICollection<Medical_Appointments> Medical_Appointmentsfk_DoctorNavigation { get; set; } = new List<Medical_Appointments>();

    public virtual ICollection<Medical_Appointments> Medical_Appointmentsfk_PatientNavigation { get; set; } = new List<Medical_Appointments>();

    public virtual Consultories fk_ConsultoryNavigation { get; set; }

    public virtual Roles fk_RoleNavigation { get; set; }

    public virtual Sexes fk_SexNavigation { get; set; }

    public virtual Types fk_TypeNavigation { get; set; }
}